# 窗框宽度
WINDOW_PADDING = 8
# 最小块单位大小
BLOCK = 60

# 游戏区域
GAME_WIDTH = 13 * BLOCK
GAME_HEIGHT = 13 * BLOCK

# 列表信息窗体
INFO_WIDTH = 6 * BLOCK
INFO_HEIGHT = GAME_HEIGHT

# 窗体的参数
WINDOW_WIDTH = 13 * BLOCK + 3 * WINDOW_PADDING + INFO_WIDTH
WINDOW_HEIGHT = 13 * BLOCK + 2 * WINDOW_PADDING
